const actionTypes = {
  NEWS_FETCH_REQUESTED: 'NEWS_FETCH_REQUESTED',
  NEWS_FETCH_SUCCEEDED: 'NEWS_FETCH_SUCCEEDED',

  ADD_NEWS_REQUESTED: 'ADD_NEWS_REQUESTED',
  ADD_NEWS_SUCCEEDED: 'ADD_NEWS_SUCCEEDED',
  ADD_NEWS_FAILED: 'ADD_NEWS_FAILED',

  EDIT_PROFILE_REQUESTED: 'EDIT_PROFILE_REQUESTED',
  EDIT_PROFILE_SUCCEEDED: 'EDIT_PROFILE_SUCCEEDED',
  EDIT_PROFILE_FAILED: 'EDIT_PROFILE_FAILED',

  AUTH_LOGIN_FETCH_REQUESTED: 'AUTH_LOGIN_FETCH_REQUESTED',
  AUTH_LOGIN_FETCH_SUCCEEDED: 'AUTH_LOGIN_FETCH_SUCCEEDED',

  AUTH_REGISTRATION_FETCH_REQUESTED: 'AUTH_REGISTRATION_FETCH_REQUESTED',
  AUTH_REGISTRATION_FETCH_SUCCEEDED: 'AUTH_REGISTRATION_FETCH_SUCCEEDED',

  AUTH_REGISTRATION_GOOGLE_FETCH_REQUESTED: 'AUTH_REGISTRATION_GOOGLE_FETCH_REQUESTED',
  AUTH_REGISTRATION_GOOGLE_FETCH_SUCCEEDED: 'AUTH_REGISTRATION_GOOGLE_FETCH_SUCCEEDED',

  AUTH_LOGOUT_FETCH_REQUESTED: 'AUTH_LOGOUT_FETCH_REQUESTED',

  WHO_AM_I_FETCH_REQUESTED: 'WHO_AM_I_FETCH_REQUESTED',

  AUTH_FETCH_FAILED: 'AUTH_FETCH_FAILED',

  USER_FETCH_REQUESTED: 'USER_FETCH_REQUESTED',
  USER_FETCH_SUCCEEDED: 'USER_FETCH_SUCCEEDED',
  USER_FETCH_FAILED: 'USER_FETCH_FAILED',

  SET_USER_LOADING: 'SET_USER_LOADING',

  RESET_STATE: 'RESET_STATE',
};

export default actionTypes;
